server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: data-collector
          uri: lb://data-collector
          predicates:
            - Path=/api/collector/**
        - id: data-consumer
          uri: lb://data-consumer
          predicates:
            - Path=/api/consumer/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
